/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrCodesRouteImport } from './routes/qr-codes'
import { Route as ApiCronMarkAbsentRouteImport } from './routes/api/cron/mark-absent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodesRoute = QrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMarkAbsentRoute = ApiCronMarkAbsentRouteImport.update({
  id: '/api/cron/mark-absent',
  path: '/api/cron/mark-absent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qr-codes': typeof QrCodesRoute
  '/api/cron/mark-absent': typeof ApiCronMarkAbsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qr-codes': typeof QrCodesRoute
  '/api/cron/mark-absent': typeof ApiCronMarkAbsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qr-codes': typeof QrCodesRoute
  '/api/cron/mark-absent': typeof ApiCronMarkAbsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/qr-codes' | '/api/cron/mark-absent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/qr-codes' | '/api/cron/mark-absent'
  id: '__root__' | '/' | '/qr-codes' | '/api/cron/mark-absent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QrCodesRoute: typeof QrCodesRoute
  ApiCronMarkAbsentRoute: typeof ApiCronMarkAbsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-codes': {
      id: '/qr-codes'
      path: '/qr-codes'
      fullPath: '/qr-codes'
      preLoaderRoute: typeof QrCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/mark-absent': {
      id: '/api/cron/mark-absent'
      path: '/api/cron/mark-absent'
      fullPath: '/api/cron/mark-absent'
      preLoaderRoute: typeof ApiCronMarkAbsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QrCodesRoute: QrCodesRoute,
  ApiCronMarkAbsentRoute: ApiCronMarkAbsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
